refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l} - {m}\n"
  rolling:
    kind: rolling_file
    path: "logs/log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l} - {m}\n"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: "logs/log.{}.gz"
        base: 1
        count: 5

root:
  level: info
  appenders:
    - stdout
    - rolling
